name: Commitlint

on:
  pull_request:

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        if: github.event.pull_request.user.login != 'dependabot[bot]'
